version: "3.9"
services:
  g11:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    container_name: peopleGroup11
    stdin_open: true
    tty: true
    command: /bin/bash
    networks:
      - network-1
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 80M
        reservations:
          cpus: '0.05'
          memory: 50M
  g21:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    container_name: peopleGroup21
    stdin_open: true
    tty: true
    command: /bin/bash
    networks:
      - network-1
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 80M
        reservations:
          cpus: '0.05'
          memory: 50M
  v11:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    container_name: video11
    stdin_open: true
    tty: true
    command: /bin/bash
    networks:
      - network-1
    deploy:
      resources:
        limits:
          cpus: '0.33'
          memory: 100M
        reservations:
          cpus: '0.2'
          memory: 80M
  g12:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    container_name: peopleGroup12
    stdin_open: true
    tty: true
    command: /bin/bash
    networks:
      - network-2
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 80M
        reservations:
          cpus: '0.05'
          memory: 50M
  v12:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    container_name: video12
    stdin_open: true
    tty: true
    command: /bin/bash
    networks:
      - network-2
    deploy:
      resources:
        limits:
          cpus: '0.33'
          memory: 100M
        reservations:
          cpus: '0.2'
          memory: 80M
networks:
  network-1:
    external:
      name: n1
  network-2:
    external:
      name: n2
